---
  - name: Install docker
    shell: curl https://get.docker.com | sh

  - name: Install docker and some dependencies
    apt:
      name: python3-pip
      state: present

  - name: Modify Docker Group
    become: true
    shell: usermod -aG docker vagrant

  - name: Set Artefact DOCKER.SOCK
    become: true
    shell: setfacl --modify user:$USER:rw /var/run/docker.sock

  - name: Change privilege of docker
    become: yes
    file: dest=/usr/bin/docker mode=+x

  - name: Start docker service
    service:
      name: docker
      state: started

  - name: Install docker python module
    pip:
      name:
        - docker
        - docker-compose
